name: sanpo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1 # Dart SDKのバージョン

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # iOSスタイルアイコン
  geolocator: ^14.0.2 # 位置情報取得
  flutter_map: ^8.1.1 # 地図表示
  firebase_core: ^2.28.0 # Firebaseコア機能
  cloud_firestore: ^4.16.0 # Cloud Firestoreデータベース
  latlong2: ^0.9.1 # 緯度経度計算 (flutter_mapの依存)
  intl: ^0.19.0 # 日付フォーマット (最新版に修正)

  # 以下のパッケージは現在のアプリの機能には不要なので削除しました
  # device_preview: ^1.3.1 # デバイスプレビューツール (開発用、必要なら残す)
  # google_maps_flutter: ^2.12.3 # Google Maps (flutter_mapと併用しないなら削除)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
