// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2yLNXm3-gDPQ_HVur3Tmr3PKjWqVxsR8',
    appId: '1:238131386241:web:a56fddfc27043ca1387a80',
    messagingSenderId: '238131386241',
    projectId: 'sanpo-app-4ba2b',
    authDomain: 'sanpo-app-4ba2b.firebaseapp.com',
    storageBucket: 'sanpo-app-4ba2b.firebasestorage.app',
    measurementId: 'G-T5W9TLEQY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2iqc9bHfsRYrJWD-03uaYVGT4Wqw9cIE',
    appId: '1:238131386241:android:dc29884a458a6a92387a80',
    messagingSenderId: '238131386241',
    projectId: 'sanpo-app-4ba2b',
    storageBucket: 'sanpo-app-4ba2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbT6DYQELnF8P-5W2CjzXX6qryziK66GU',
    appId: '1:238131386241:ios:329ecc493782ac1f387a80',
    messagingSenderId: '238131386241',
    projectId: 'sanpo-app-4ba2b',
    storageBucket: 'sanpo-app-4ba2b.firebasestorage.app',
    iosBundleId: 'com.example.sanpoApp',
  );

}